version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}